import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Trim Proof handles analytics, email signups, billing, AI-generated assets, and print proof data.",
  alternates: {
    canonical: "/privacy"
  }
};

const sections = [
  {
    heading: "What Trim Proof collects",
    body:
      "Trim Proof collects the information needed to run the service: account email, name, company, role, optional phone and website, print-volume/use-case details, print briefs you enter, generated proof metadata, selected product and prepress settings, billing email addresses, checkout status, and operational logs for security and reliability."
  },
  {
    heading: "Analytics and conversion measurement",
    body:
      "Trim Proof uses Google Analytics 4 and may use Google Tag Manager to measure page views, dummy proof starts, advanced mode use, checkout starts, proof exports, purchases, and email signups. Server-side Google Analytics events use the browser's GA client and session identifiers when available so conversion reporting can connect to the original site visit. Trim Proof does not send email addresses, payment card data, or direct personal contact details to Google Analytics event parameters."
  },
  {
    heading: "Payments",
    body:
      "Stripe processes one-time export credits and Trim Proof Pro subscriptions. Trim Proof stores checkout session IDs, customer IDs, customer email addresses, entitlement type, checkout mode, order status, refund or expiration status, and export-credit usage state so paid access can be verified and managed."
  },
  {
    heading: "Email",
    body:
      "If you join the launch list or request an access link, Trim Proof stores the email address and sends transactional messages through the configured email provider. These messages can include launch updates, access links, admin notifications, or confirmation emails related to your request."
  },
  {
    heading: "AI and proof generation",
    body:
      "Trim Proof can send creative asset prompts, layout context, and non-sensitive design brief details to configured image providers such as OpenAI or Google Gemini. Final PDF geometry, vector text, bleed, crop marks, color workflow, and preflight checks are generated by Trim Proof's deterministic prepress pipeline."
  },
  {
    heading: "Data storage and service providers",
    body:
      "Trim Proof uses Supabase for application data, Stripe for billing, SendGrid or Resend for transactional email, Google Analytics for measurement, and configured AI providers for creative image generation. Generated files may be stored on the application server for download and operational verification."
  },
  {
    heading: "Your choices",
    body:
      "Demo proof mode requires an account. You can avoid paid checkout storage by not buying an export credit or starting Pro. You can request access-link emails only for the signed-in account email tied to an active subscription or unused export credit."
  },
  {
    heading: "Contact",
    body:
      "For privacy or data questions, contact Trim Proof at support@trimproof.com."
  }
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4">
          <Link className="font-display text-lg font-bold text-surface-ink" href="/">
            Trim Proof
          </Link>
          <Link className="text-sm font-semibold text-muted transition hover:text-surface-ink" href="/signup?intent=demo&next=/app">
            Create account
          </Link>
        </div>
      </header>

      <section className="mx-auto max-w-5xl px-4 py-14">
        <p className="text-sm font-bold uppercase text-brand">Privacy Policy</p>
        <h1 className="mt-3 font-display text-5xl font-bold leading-[1.05] text-surface-ink">
          How Trim Proof handles service, billing, analytics, and proof data.
        </h1>
        <p className="mt-5 max-w-3xl text-base leading-7 text-muted">
          Effective June 5, 2026. This policy describes the current Trim Proof web application at trimproof.com.
        </p>
      </section>

      <section className="border-y border-border bg-surface">
        <div className="mx-auto grid max-w-5xl gap-4 px-4 py-12">
          {sections.map((section) => (
            <article key={section.heading} className="rounded-[8px] border border-border bg-background p-5">
              <h2 className="font-display text-2xl font-bold text-surface-ink">{section.heading}</h2>
              <p className="mt-3 text-base leading-7 text-muted">{section.body}</p>
            </article>
          ))}
        </div>
      </section>
    </main>
  );
}
